In [1]:
import os
import pandas as pd
from utils import network_creation, target_definition, features_generation
import pyarrow.parquet as pq
import pyarrow as pa

In [ ]:
os.makedirs("data", exist_ok=True)

TRAIN_PATH = "data/split/train_pairs.parquet"
VAL_PATH = "data/split/validation_pairs.parquet"
TEST_PATH = "data/split/test_pairs.parquet"

# load the file 
train = pd.read_parquet(TRAIN_PATH)
val = pd.read_parquet(VAL_PATH)
test = pd.read_parquet(TEST_PATH)

# 1. Create the Network

In [ ]:
net_train = network_creation(train)
net_val = network_creation(val, "article_id", "ref_id", "is_reference_valid")
net_test = network_creation(test, "article_id", "ref_id", "is_reference_valid")

# 2. Generate the graph Features

In [4]:
#final_train = features_generation(net_train, train_def)
final_val = features_generation(net_val, val, "article_id", "ref_id")
final_test = features_generation(net_test, test, "article_id", "ref_id")

In [ ]:
print("final dataset for TRAIN set:")
display(final_train.head())
print("\nfinal dataset for VALIDATION set:")
display(final_val.head())
print("\nfinal dataset for TEST set:")
display(final_test.head())

final dataset for VALIDATION set:

,article_id,ref_id,title_article,lang_article,doc_type_article,abstract_article,year_article,n_citation_article,keywords_article,authors_article,...,in_ref,out_ref,pagerank_ref,avg_neigh_degree_ref,katz_cent_ref,degree_ratio,pagerank_ratio,pagerank_prod,common_neighbors,jaccard_coeff
0,56d8c6addabfae2eee533da3,56d87f43dabfae2eee59ffc6,GATSF: Genetic algorithm to save fuel,en,conference,This paper proposes the use of a genetic algor...,2012.0,3.0,"[fuel, energy conservation, genetic algorithms...","[{'id': '53f44adbdabfaedd74e00ac3', 'name': 'v...",...,12,6,0.000026,0.5,0.004139,0.142857,0.106881,6.985432e-11,0,0.000000
1,53e9b532b7602d9704068778,53909eef20f70186a0e361ad,Some Properties of Weak Uninorms,en,journal,A weak uninorm is not only a generalization of...,2011.0,20.0,"[Uninorm, Nullnorm, Weak uninorm, Archimedean,...","[{'id': '6372ad0aec88d95668d0c7bf', 'name': 'W...",...,2,1,0.000006,0.0,0.002205,2.000000,0.495487,1.506614e-11,1,0.166667
2,53e9b532b7602d9704068778,573695696e3b12023e48edff,Some Properties of Weak Uninorms,en,journal,A weak uninorm is not only a generalization of...,2011.0,20.0,"[Uninorm, Nullnorm, Weak uninorm, Archimedean,...","[{'id': '6372ad0aec88d95668d0c7bf', 'name': 'W...",...,6,0,0.000014,0.0,0.003014,4.000000,0.194915,3.830338e-11,1,0.111111
3,53e9b532b7602d9704068778,539098b820f70186a0e0b338,Some Properties of Weak Uninorms,en,journal,A weak uninorm is not only a generalization of...,2011.0,20.0,"[Uninorm, Nullnorm, Weak uninorm, Archimedean,...","[{'id': '6372ad0aec88d95668d0c7bf', 'name': 'W...",...,57,0,0.000238,0.0,0.015798,4.000000,0.011487,6.500086e-10,0,0.000000
4,53e9b532b7602d9704068778,5390ae2e20f70186a0ec8984,Some Properties of Weak Uninorms,en,journal,A weak uninorm is not only a generalization of...,2011.0,20.0,"[Uninorm, Nullnorm, Weak uninorm, Archimedean,...","[{'id': '6372ad0aec88d95668d0c7bf', 'name': 'W...",...,1,1,0.000003,2.0,0.002021,2.000000,0.830609,8.986370e-12,0,0.000000

final dataset for TEST set:

,article_id,ref_id,title_article,lang_article,doc_type_article,abstract_article,year_article,n_citation_article,keywords_article,authors_article,...,in_ref,out_ref,pagerank_ref,avg_neigh_degree_ref,katz_cent_ref,degree_ratio,pagerank_ratio,pagerank_prod,common_neighbors,jaccard_coeff
0,6426ed4790e50fcafd445e7f,5d7f5db647c8f76646dc5cc6,A Deep Active Learning Framework with Informat...,en,conference,Acquiring medical images and their segmentatio...,2022.0,14.0,"[medical image segmentation, deep active learn...","[{'id': '63274950a95e4d1d05572ceb', 'name': 'K...",...,12,1,0.000025,1.0,0.003847,0.500000,0.107447,6.839931e-11,0,0.0
1,5ff8836091e011c832672f54,57d063e0ac44367354294940,An Efficient Implementation of NTRU Encryption...,en,conference,The Internet of Things (IoT) or the Internet o...,2020.0,12.0,"[IoT, protocol, sensor nodes, secured communic...","[{'id': '', 'name': 'Y. M. Agus', 'org': 'Scho...",...,2,0,0.000006,0.0,0.002048,1.000000,0.417491,1.760150e-11,0,0.0
2,66ecda9201d2a3fbfcdf8856,5f35115a91e011e2b713e155,Architectural Co-LOD Generation,en,journal,Managing the level-of-detail (LOD) in architec...,2024.0,35.0,"[3D generation, structural reconstruction, lev...","[{'id': '', 'name': 'Runze Zhang', 'org': 'She...",...,3,0,0.000008,0.0,0.002234,2.000000,0.345497,2.126983e-11,0,0.0
3,66ecda9201d2a3fbfcdf8856,6456389bd68f896efacf6bbb,Architectural Co-LOD Generation,en,journal,Managing the level-of-detail (LOD) in architec...,2024.0,35.0,"[3D generation, structural reconstruction, lev...","[{'id': '', 'name': 'Runze Zhang', 'org': 'She...",...,1,3,0.000004,2.0,0.001862,0.500000,0.701852,1.046901e-11,0,0.0
4,61dd5fb55244ab9dcb8bddef,5a39cb9a0cf29b02debe17e8,Technological and Digital Interventions for Me...,en,journal,Background: Research increasingly shows how se...,2021.0,27.0,"[digital applications (apps), digital mental h...","[{'id': '5611b29945ce1e5962909cf2', 'name': 'N...",...,13,2,0.000035,0.0,0.004091,0.333333,0.141959,1.769699e-10,0,0.0