In [1]:
import os
import pandas as pd
from utils import network_creation, target_definition, features_generation

In [2]:
os.makedirs("data", exist_ok=True)

TRAIN_PATH = "data/split/train.parquet"
VAL_PATH = "data/split/validation.parquet"
TEST_PATH = "data/split/test.parquet"

# load the file 
train = pd.read_parquet(TRAIN_PATH)
val = pd.read_parquet(VAL_PATH)
test = pd.read_parquet(TEST_PATH)

In [3]:
train = train.head(10000)
val = val.head(10000)
test = test.head(10000)

# 1. Create the Network

In [4]:
net_train = network_creation(train)
net_val = network_creation(val)
net_test = network_creation(test)

# 2. Configure pairs of paper with target labels

In [5]:
train_def = target_definition(net_train)
val_def = target_definition(net_val)
test_def = target_definition(net_test)

# 3. Generate the graph Features

In [6]:
final_train = features_generation(net_train, train_def)
final_val = features_generation(net_val, val_def)
final_test = features_generation(net_test, test_def)

In [7]:
print("final dataset for TRAIN set:")
display(final_train.head())
print("\nfinal dataset for VALIDATION set:")
display(final_val.head())
print("\nfinal dataset for TEST set:")
display(final_test.head())

final dataset for TRAIN set:

,node_a,node_b,Target,in_a,out_a,pagerank_a,eigen_cent_a,avg_neigh_degree_a,katz_cent_a,in_b,out_b,pagerank_b,eigen_cent_b,avg_neigh_degree_b,katz_cent_b,degree_ratio,pagerank_ratio,pagerank_prod,common_neighbors,jaccard_coeff
0,58437777ac44360f1083feb4,53e9a508b7602d9702e292db,1,0,16,0.000009,2.336432e-08,0.0,0.002823,1,0,0.000010,4.906508e-07,0.0,0.003106,16.0,0.945791,8.898561e-11,0,0.0
1,58437777ac44360f1083feb4,5550449945ce0a409eb4f299,1,0,16,0.000009,2.336432e-08,0.0,0.002823,1,0,0.000010,4.906508e-07,0.0,0.003106,16.0,0.945791,8.898561e-11,0,0.0
2,58437777ac44360f1083feb4,555044af45ce0a409eb4ff7c,1,0,16,0.000009,2.336432e-08,0.0,0.002823,1,0,0.000010,4.906508e-07,0.0,0.003106,16.0,0.945791,8.898561e-11,0,0.0
3,58437777ac44360f1083feb4,5390b68720f70186a0f1b70b,1,0,16,0.000009,2.336432e-08,0.0,0.002823,6,0,0.000012,2.827083e-06,0.0,0.004517,16.0,0.768748,1.094812e-10,0,0.0
4,58437777ac44360f1083feb4,539099a220f70186a0e183fc,1,0,16,0.000009,2.336432e-08,0.0,0.002823,4,0,0.000011,1.892510e-06,0.0,0.003953,16.0,0.870363,9.669816e-11,0,0.0

final dataset for VALIDATION set:

,node_a,node_b,Target,in_a,out_a,pagerank_a,eigen_cent_a,avg_neigh_degree_a,katz_cent_a,in_b,out_b,pagerank_b,eigen_cent_b,avg_neigh_degree_b,katz_cent_b,degree_ratio,pagerank_ratio,pagerank_prod,common_neighbors,jaccard_coeff
0,607d5a7891e011772416d953,599c7b25601a182cd27104b1,1,0,1,0.000009,4.262665e-08,0.0,0.002818,1,0,0.000018,8.525331e-07,0.0,0.003100,1.0,0.522060,1.607113e-10,0,0.0
1,53e9ac69b7602d970363a464,5390b64020f70186a0f198ca,1,0,9,0.000009,4.262665e-08,0.0,0.002818,1,0,0.000010,8.525331e-07,0.0,0.003100,9.0,0.907591,9.243972e-11,0,0.0
2,53e9ac69b7602d970363a464,53e9ace8b7602d97036c35a1,1,0,9,0.000009,4.262665e-08,0.0,0.002818,2,0,0.000011,1.662440e-06,0.0,0.003381,9.0,0.859961,9.756009e-11,0,0.0
3,53e9ac69b7602d970363a464,5390b56a20f70186a0f05c88,1,0,9,0.000009,4.262665e-08,0.0,0.002818,1,0,0.000010,8.525331e-07,0.0,0.003100,9.0,0.907591,9.243972e-11,0,0.0
4,53e9ac69b7602d970363a464,5390a1e620f70186a0e59c35,1,0,9,0.000009,4.262665e-08,0.0,0.002818,2,0,0.000010,1.662440e-06,0.0,0.003381,9.0,0.878400,9.551194e-11,0,0.0

final dataset for TEST set:

,node_a,node_b,Target,in_a,out_a,pagerank_a,eigen_cent_a,avg_neigh_degree_a,katz_cent_a,in_b,out_b,pagerank_b,eigen_cent_b,avg_neigh_degree_b,katz_cent_b,degree_ratio,pagerank_ratio,pagerank_prod,common_neighbors,jaccard_coeff
0,555043a445ce0a409eb488e9,53e9a20fb7602d9702b1222c,1,0,12,0.000009,2.137785e-08,0.0,0.002783,1,0,0.00001,4.489348e-07,0.0,0.003061,12.0,0.929157,8.628743e-11,0,0.0
1,555043a445ce0a409eb488e9,53e9b0c2b7602d9703b35dac,1,0,12,0.000009,2.137785e-08,0.0,0.002783,1,0,0.00001,4.489348e-07,0.0,0.003061,12.0,0.929157,8.628743e-11,0,0.0
2,555043a445ce0a409eb488e9,53e9a97ab7602d97032d2a15,1,0,12,0.000009,2.137785e-08,0.0,0.002783,1,0,0.00001,4.489348e-07,0.0,0.003061,12.0,0.929157,8.628743e-11,0,0.0
3,555043a445ce0a409eb488e9,5390a25820f70186a0e5f25c,1,0,12,0.000009,2.137785e-08,0.0,0.002783,1,0,0.00001,4.489348e-07,0.0,0.003061,12.0,0.929157,8.628743e-11,0,0.0
4,555043a445ce0a409eb488e9,53e99e13b7602d97026d6e31,1,0,12,0.000009,2.137785e-08,0.0,0.002783,1,0,0.00001,4.489348e-07,0.0,0.003061,12.0,0.929157,8.628743e-11,0,0.0